language:
  - cpp

compiler:
  - gcc
  - clang

dist: trusty
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - lcov
     
     
before_install:
  # C++14, even C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq 

script:
  # Checks
  - g++ --version
  - gcc --version
  - gcov --version
  # Build
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug
  # Run test
  - valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./../bin/mini_yaml_test
  
#after_success:
#  - lcov --directory ./CMakeFiles/mini_yaml.dir --capture --output-file coverage.info #Or remove '*/tests/*'
#  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
#  - lcov --list coverage.info
#  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
