language:
  - cpp

compiler:
  - gcc
  - clang

dist: trusty
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - lcov
     
     
before_install:
  # C++11, C++14, even C++17...
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90

script:
  # Checks
  - g++ --version
  - gcc --version
  - gcov --version
  # Build
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug
  # Run test
  - cd ../bin
  - valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./mini_yaml_test
  - cd ../build
  
after_success:
  - lcov --directory ./CMakeFiles/mini_yaml_test.dir --capture --output-file coverage.info
  - lcov --extract coverage.info '*/yaml.hpp' '*/yaml.cpp' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
